### ISSUE TITLE
Wishlist:  Podman

### ISSUE THREAD

**Issue by zachab4** [codekow/ocp-code-server#7]
Adding Podman to code server would allow users to test their containers and builds directly without needing a namespace.

[Red Hat:  podman-inside-container](https://www.redhat.com/sysadmin/podman-inside-container)
[Red Hat:  podman-inside-kubernetes](https://www.redhat.com/sysadmin/podman-inside-kubernetes)

**Comment by codekow** [comment]
The `oc` command is actually there for this purpose.  

Without some modification to a standard OpenShift platform, it would be difficult to run `docker` or `podman` within a container due to kernel userspace. In general, you don't want to run `podman` in a container.

Look at what you can do with the `oc` command. Some inspiration includes the following:

`oc run -it --rm random-pod httpd -- /bin/sh`

OR

https://stackoverflow.com/questions/47260933/how-to-build-and-deploy-an-app-from-local-directory
You can do 'binary' builds for a Dockerfile that is local to the oc command.
